name: Upload-Download Artifact Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t my-docker-image .
        docker save -o my-docker-image.tar my-docker-image
      shell: bash

    - name: Archive Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image-artifact
        path: my-docker-image.tar
