name: dockerjob

on: push

jobs:
  first_job:
   runs-on: ubuntu-latest
   steps:
   - name: git checkout
     uses: actions/checkout@v4
   - name: docker install
     run: |
      sudo apt update
      sudo apt install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      apt-cache policy docker-ce
      sudo apt install docker-ce
      sudo systemctl status docker
      
   - name: list files
     run: ls
