name: dockerimagebuild
on: push
env:
  DOCKER_USERNAME: chowdarybvsn
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: custom-nginx
jobs:
  docker:
     runs-on: ubuntu-latest
     steps:
     - name: build
       run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
     - name: login
       run:  echo docker login --Username=${{ env.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
     - name: pushing
       run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker deploy
      run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
     